import Foundation
import CommonCrypto

/// A backup keybag unlocked with the user's password: the host-recoverable class keys.
public struct UnlockedKeybag: Sendable {
    /// Protection class → unwrapped 32-byte AES class key. Contains only passcode-wrapped
    /// classes; device-only classes (unwrappable solely with an on-device key) are absent.
    public let classKeys: [UInt32: Data]
    public init(classKeys: [UInt32: Data]) { self.classKeys = classKeys }
}

/// Parses an Apple backup `BackupKeyBag` (the `Manifest.plist` `BackupKeyBag` TLV) and unwraps
/// its class keys from the backup password.
///
/// Algorithm pinned by `docs/superpowers/sp2/wp4.design.odb.md` (BINDING), cross-checked against
/// richinfante / dunhamsteve / MVT / avibrazil / dinosec — the vendored libimobiledevice carries
/// no keybag code (key wrapping happens on the device). The synthetic test fixture is generated by
/// an independent implementation (`Scripts/wp4-keybag-oracle.py`) so a derivation bug cannot hide.
///
/// KEK derivation (do NOT swap the hashes):
///   temp = PBKDF2-HMAC-SHA256(password, DPSL, DPIC, 32)   // inner
///   KEK  = PBKDF2-HMAC-SHA1 (temp,     SALT, ITER, 32)    // outer
public struct Keybag {
    /// `WRAP & WRAP_PASSCODE` marks a class whose key the host can unwrap from the password.
    /// Classes without this bit are device-only and must be skipped, not unwrapped.
    private static let wrapPasscode: UInt32 = 2

    /// Upper bound on the PBKDF2 round counts (`ITER`, `DPIC`). A hostile/corrupt keybag with
    /// `ITER = 0xFFFFFFFF` would otherwise wedge `unlock()` in PBKDF2 for minutes-to-hours (a
    /// soft-DoS on `verify --level crypto` / `extract` — Odb G1).
    ///
    /// Checkpoint C run 2 (real iOS 27 keybag, lead-verified TLV parse): the device's outer
    /// `ITER` is 10,000 and its inner `DPIC` is EXACTLY 10,000,000 — the previous 10^7 ceiling sat
    /// right on the real DPIC. The bound check is `<=`, so 10,000,000 was admitted; but a value
    /// pinned to the cap is brittle (any device bump dies as `malformedKeybag`). Raised to
    /// 5×10^7 — 5× the real DPIC, comfortably clear of legitimate keybags yet still a fast reject
    /// for a `0xFFFFFFFF` (~4.3×10^9) hostile one, so the DoS bound stays meaningful.
    private static let maxRounds: UInt32 = 50_000_000

    private let salt: Data
    private let dpsl: Data
    private let iter: UInt32
    private let dpic: UInt32
    private let wrappedClassKeys: [(clas: UInt32, wrap: UInt32, wpky: Data)]

    public init(tlv: Data) throws {
        let fields = try Self.parseTLV(tlv)

        // Version / type gate: fail loudly on an unknown keybag rather than mis-derive (R5/spec §6).
        guard let typeField = fields.header["TYPE"], Self.beUInt32(typeField) == 1 else {
            throw KeybagError.malformedKeybag
        }
        // Accept VERS 3, 4, and 5. Checkpoint C run 2 (real iOS 27 keybag, lead-verified read-only
        // TLV parse of the 1712-byte BackupKeyBag from staging): VERS=5 carries the IDENTICAL wire
        // format as 3/4 — VERS/TYPE/UUID/HMCK/WRAP/SALT/ITER/DPWT/DPIC/DPSL header then 14 class
        // blocks (UUID/CLAS/WRAP/KTYP/WPKY), clean parse, zero trailing bytes, double-protection
        // trio present (DPWT=1). Semantics are confirmed empirically by device checkpoint C run 3:
        // if VERS-5 semantics differed, unlock fails CLOSED (wrongPassword / malformedKeybag), never
        // silently. An unknown version still rejects loudly below — the tripwire stays armed.
        let version = fields.header["VERS"].map(Self.beUInt32) ?? 0
        guard version == 3 || version == 4 || version == 5 else {
            throw KeybagError.unsupportedKeybagVersion(version: Int(version))
        }

        guard let salt = fields.header["SALT"],
              let dpsl = fields.header["DPSL"],
              let iterField = fields.header["ITER"],
              let dpicField = fields.header["DPIC"] else {
            throw KeybagError.malformedKeybag
        }
        self.salt = salt
        self.dpsl = dpsl
        self.iter = Self.beUInt32(iterField)
        self.dpic = Self.beUInt32(dpicField)
        self.wrappedClassKeys = fields.classes
        guard self.iter > 0, self.dpic > 0 else { throw KeybagError.malformedKeybag }
        // Reject an oversized round count BEFORE running PBKDF2 — fail fast, never wedge (G1).
        guard self.iter <= Self.maxRounds, self.dpic <= Self.maxRounds else {
            throw KeybagError.malformedKeybag
        }
    }

    public func unlock(password: String) throws -> UnlockedKeybag {
        let kek = try Self.deriveKEK(password: password, dpsl: dpsl, dpic: dpic, salt: salt, iter: iter)

        var classKeys: [UInt32: Data] = [:]
        var passcodeClassCount = 0
        var unwrapFailures = 0
        for entry in wrappedClassKeys {
            // Skip device-only classes: the host has no device key to unwrap them (R3).
            guard entry.wrap & Self.wrapPasscode != 0 else { continue }
            passcodeClassCount += 1
            if let key = Self.rfc3394Unwrap(kek: kek, wrapped: entry.wpky) {
                classKeys[entry.clas] = key
            } else {
                unwrapFailures += 1
            }
        }

        // A correct password unwraps every passcode-wrapped class; a wrong one unwraps none.
        // Zero successes ⇒ wrong password. A partial failure means the keybag is inconsistent.
        if passcodeClassCount > 0 && classKeys.isEmpty {
            throw KeybagError.wrongPassword
        }
        if unwrapFailures > 0 {
            throw KeybagError.malformedKeybag
        }
        return UnlockedKeybag(classKeys: classKeys)
    }

    // MARK: - TLV parsing

    private struct ParsedTLV {
        var header: [String: Data]
        var classes: [(clas: UInt32, wrap: UInt32, wpky: Data)]
    }

    /// Walks the big-endian `TAG`(4B) + `LEN`(4B BE) + `PAYLOAD` stream.
    ///
    /// Header fields precede the first class block. A class block is delimited by a leading
    /// `UUID` *or* `CLAS` (Q2: real blocks may lead with `UUID`, so splitting on `CLAS` alone
    /// mis-parses). Once class parsing has begun, a `CLAS` or per-class `UUID` flushes the
    /// previous block and opens a new one; the keybag-level `UUID` that appears before the first
    /// `CLAS` stays in the header.
    private static func parseTLV(_ data: Data) throws -> ParsedTLV {
        var header: [String: Data] = [:]
        var classes: [(clas: UInt32, wrap: UInt32, wpky: Data)] = []

        var current: [String: Data]? = nil      // the open class block, once class parsing begins
        var inClassSection = false               // flipped by the first CLAS tag

        func flush() {
            defer { current = nil }
            guard let block = current,
                  let clasField = block["CLAS"], let wpky = block["WPKY"] else { return }
            let wrap = block["WRAP"].map(beUInt32) ?? 0
            classes.append((clas: beUInt32(clasField), wrap: wrap, wpky: wpky))
        }

        let bytes = [UInt8](data)
        var offset = 0
        while offset + 8 <= bytes.count {
            let tag = String(decoding: bytes[offset..<offset + 4], as: UTF8.self)
            let length = Int(beUInt32(Data(bytes[offset + 4..<offset + 8])))
            let valueStart = offset + 8
            guard valueStart + length <= bytes.count else { throw KeybagError.malformedKeybag }
            let value = Data(bytes[valueStart..<valueStart + length])
            offset = valueStart + length

            switch tag {
            case "CLAS":
                flush()                          // close the prior block if any
                inClassSection = true
                current = ["CLAS": value]
            case "UUID" where inClassSection:
                flush()                          // a fresh per-class UUID opens the next block
                current = [:]
            case "UUID":
                header["UUID"] = value           // keybag-level UUID (before any class block)
            default:
                if current != nil { current?[tag] = value } else { header[tag] = value }
            }
        }
        flush()
        guard offset == bytes.count else { throw KeybagError.malformedKeybag }
        return ParsedTLV(header: header, classes: classes)
    }

    private static func beUInt32(_ data: Data) -> UInt32 {
        var value: UInt32 = 0
        for byte in data.prefix(4) { value = (value << 8) | UInt32(byte) }
        return value
    }

    // MARK: - crypto

    /// Corrected double-PBKDF2 (inner SHA256 over DPSL/DPIC, outer SHA1 over SALT/ITER), 32B out.
    private static func deriveKEK(password: String, dpsl: Data, dpic: UInt32,
                                  salt: Data, iter: UInt32) throws -> Data {
        let pw = Data(password.utf8)
        let temp = try pbkdf2(prf: CCPseudoRandomAlgorithm(kCCPRFHmacAlgSHA256),
                              password: pw, salt: dpsl, rounds: dpic, keyLength: 32)
        return try pbkdf2(prf: CCPseudoRandomAlgorithm(kCCPRFHmacAlgSHA1),
                          password: temp, salt: salt, rounds: iter, keyLength: 32)
    }

    private static func pbkdf2(prf: CCPseudoRandomAlgorithm, password: Data, salt: Data,
                               rounds: UInt32, keyLength: Int) throws -> Data {
        var derived = Data(count: keyLength)
        let status = derived.withUnsafeMutableBytes { derivedPtr -> Int32 in
            password.withUnsafeBytes { pwPtr in
                salt.withUnsafeBytes { saltPtr in
                    CCKeyDerivationPBKDF(
                        CCPBKDFAlgorithm(kCCPBKDF2),
                        pwPtr.baseAddress?.assumingMemoryBound(to: CChar.self), password.count,
                        saltPtr.baseAddress?.assumingMemoryBound(to: UInt8.self), salt.count,
                        prf, rounds,
                        derivedPtr.baseAddress?.assumingMemoryBound(to: UInt8.self), keyLength)
                }
            }
        }
        guard status == kCCSuccess else { throw KeybagError.malformedKeybag }
        return derived
    }

    /// RFC 3394 AES key unwrap via CommonCrypto. Returns nil on the integrity-check failure that
    /// signals a wrong KEK (wrong password) — the `0xA6×8` register mismatch surfaces as
    /// `kCCDecodeError`.
    static func rfc3394Unwrap(kek: Data, wrapped: Data) -> Data? {
        guard wrapped.count >= 24, wrapped.count % 8 == 0 else { return nil }
        var rawLength = CCSymmetricUnwrappedSize(CCWrappingAlgorithm(kCCWRAPAES), wrapped.count)
        var raw = Data(count: rawLength)
        let status = raw.withUnsafeMutableBytes { rawPtr -> Int32 in
            kek.withUnsafeBytes { kekPtr in
                wrapped.withUnsafeBytes { wrappedPtr in
                    CCSymmetricKeyUnwrap(
                        CCWrappingAlgorithm(kCCWRAPAES),
                        CCrfc3394_iv, CCrfc3394_ivLen,
                        kekPtr.baseAddress?.assumingMemoryBound(to: UInt8.self), kek.count,
                        wrappedPtr.baseAddress?.assumingMemoryBound(to: UInt8.self), wrapped.count,
                        rawPtr.baseAddress?.assumingMemoryBound(to: UInt8.self), &rawLength)
                }
            }
        }
        guard status == kCCSuccess else { return nil }
        return raw.prefix(rawLength)
    }
}
